import numpy as np
a=np.array([1,2,3])
print("1D ARRAY",'\n',a)
b=np.array([[1,2,3],[4,5,6]])
print("2D ARRAY ",'\n',b)
marks=np.array([100,201,302,99,200])
print("MARKS ARRAY ",'\n',marks)
print("THE MAX IS ",max(marks))
print("THE MIN IS ",min(marks))
print("THE SUM IS ",sum(marks))
