CREATE DATABASE COMPANY_DB;
USE COMPANY_DB;
CREATE TABLE DEPARTMENTS (DEPT_ID INT PRIMARY KEY AUTO_INCREMENT, DEPT_NAME VARCHAR (50));
INSERT INTO Departments (DEPT_NAME) VALUES
('IT'),        
('HR'),         
('Finance'),    
('Sales'),     
('Marketing');   
SELECT * FROM DEPARTMENTS;
CREATE TABLE EMPLOYEES(EMP_ID INT PRIMARY KEY AUTO_INCREMENT,EMP_NAME VARCHAR(50),
AGE INT,
SALARY DECIMAL(10,2),
DEPT_ID INT,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID));
INSERT INTO EMPLOYEES(EMP_NAME,AGE,SALARY,DEPT_ID) VALUES
('Rahul', 28, 55000, 1),
('Priya', 32, 60000, 2),
('Arjun', 25, 48000, NULL),
('Neha', 30, 70000, 1), 
('Vikram', 35, 65000, 4); 
SELECT * FROM EMPLOYEES;
TRUNCATE TABLE EMPLOYEES;
DELETE FROM DEPARTMENTS WHERE DEPT_ID IN (1,2,3,4);
SELECT * FROM DEPARTMENTS;
ALTER TABLE Employees DROP FOREIGN KEY employees_ibfk_1;
INSERT INTO EMPLOYEES (EMP_NAME,AGE,SALARY,DEPT_ID)VALUES
('Rahul', 28, 55000, 1),
('Priya', 32, 60000, 2),
('Arjun', 25, 48000, NULL),
('Neha', 30, 70000, 1), 
('Vikram', 35, 65000, 4);
INSERT INTO Departments (DEPT_NAME) VALUES
('IT'),        
('HR'),         
('Finance'),    
('Sales'),     
('Marketing');
SELECT EMPLOYEES.EMP_NAME,EMPLOYEES.SALARY,DEPARTMENTS.DEPT_ID 
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID; 
TRUNCATE DEPARTMENTS;
INSERT INTO DEPARTMENTS (DEPT_NAME) VALUES
('IT'),        
('HR'),         
('Finance'),    
('Sales'),     
('Marketing');
SELECT EMPLOYEES.EMP_NAME,EMPLOYEES.SALARY,DEPARTMENTS.DEPT_ID 
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID; 
SELECT EMPLOYEES.EMP_NAME,EMPLOYEES.SALARY,DEPARTMENTS.DEPT_ID 
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID; 
SELECT EMPLOYEES.EMP_NAME,EMPLOYEES.SALARY,DEPARTMENTS.DEPT_ID 
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS
ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID; 
CREATE DATABASE SCHOOLDB;
USE SCHOOLDB;
DROP TABLE SUBJECTS;
CREATE TABLE SUBJECTS(SUBJECT_ID INT PRIMARY KEY AUTO_INCREMENT, SUBJECT_NAME VARCHAR(50));

INSERT INTO Subjects (subject_name) VALUES
('Mathematics'),  
('Science'),       
('English'),      
('History'),      
('Geography'); 
DROP TABLE TEACHERS;

CREATE TABLE TEACHERS(SUBJECT_ID INT, TNAME VARCHAR(50));


INSERT INTO Teachers (SUBJECT_ID ,TNAME) VALUES
(1, 'Rahul Sir'),   
(2, 'Priya Madam'), 
(NULL,'Arjun Sir'),
(3, 'Neha Madam');  
SELECT * FROM TEACHERS;
SELECT * FROM SUBJECTS;
SELECT TEACHERS.TNAME,SUBJECTS.SUBJECT_NAME
FROM TEACHERS
LEFT JOIN SUBJECTS
ON TEACHERS.SUBJECT_ID=SUBJECTS.SUBJECT_ID;

 